### ISSUE TITLE
Consider replacing bespoke terraform infrastructure with Gitpod

### ISSUE THREAD

**Issue by chuck-confluent** [ora0600/confluent-ksqldb-hands-on-workshop#3]
Awesome workshop! I love all the different use cases! I think the workshop experience could be improved with a 0 setup, 1 click, browser-based deployment of the lab infrastructure with Gitpod.

For example, see:
- https://github.com/chuck-confluent/template-confluent-cli

In short, you add a `.gitpod.yml` file and then anyone with a github account can click a button to run a pre-configured lab environment in their browser. Gitpod provides users 50 free hours per month, which is generous for workshop purposes.

**Comment by ora0600** [comment]
Thank you good idea
