### ISSUE TITLE
Feedback / Issues

### ISSUE THREAD

**Issue by pkleindl** [ora0600/confluent-ksqldb-hands-on-workshop#4]
First things first, thanks for providing this great script :-)

I used it today to set up cluster for ksql training on Confluent Cloud and noticed some things on the way.
I'll just sum them up here and create separate issues if necessary
1) It does not work for your own account because it does not show up in the invitation list (at least not for me) -> fixed by switching to the user list
2) It does not check if the attendees already exist on the cloud environment -> fixed by switching to the user list
3) If the user exists the call to invitation list still works, but the ID is used instead of the user-id for Principal -> switch to user list or use other column for consistency?
4) If a user has had two invites in the past it will only refer to the first one  -> fixed by switching to the user list
5) Existing users would be deleted globally when calling the cleanup script
6) ksql cluster delete command is wrong, missing the cluster keyword (confluent ksql cluster delete $CCLOUD_KSQLDB_ID --environment $CCLOUD_ENV)
7)  It is easier to match clusters to user if the user name ($line) is simply prefixed to the cluster-name (export CCLOUD_CLUSTERNAME=$XX_CCLOUD_CLUSTERNAME-$n-$line)
8) I created 4 environments and hit the IAM key limit for my user (which seems to be 10 by default) -> not an issue but worth mentioning
9) Reading from attendees file only works if there is a line break, I noticed this when I tried it with a single user and removed the line break.

**Comment by ora0600** [comment]
Thank you. You are right. I expect new users and the script do no cover existing users.

**Comment by ora0600** [comment]
And yes, I did change the ksqld cluster delete command to:
confluent ksql cluster delete KSQLID --environment ENVID

**Comment by ora0600** [comment]
I comment in the readme, that we do not cover existing users with the create cccloud cluster script.
Thank you for the hint

**Comment by pkleindl** [comment]
> Thank you. You are right. I expect new users and the script do no cover existing users.

It works completely fine with my little change and commenting out the delete part.
If I find a little time I can provide a PR that allows both.

**Comment by ora0600** [comment]
> > Thank you. You are right. I expect new users and the script do no cover existing users.
> 
> It works completely fine with my little change and commenting out the delete part. If I find a little time I can provide a PR that allows both.

Thank you. This would be helpful.

**Comment by ora0600** [comment]
Implemented

**Comment by ora0600** [comment]
Done
